### ISSUE TITLE
run time?

### ISSUE THREAD

**Issue by junbum766** [bardisafa/EOAL#2]
How long does the training run take on Cifar100 dataset, with a mismatch rate of 20% and other options as default?
I took 20 hours up to 5 cycles with RTX3090. Is it right for it to take this long?

**Comment by bardisafa** [comment]
Thank you for your interest in our work. In my experience, completing 10 cycles on CIFAR-100 typically takes around 20 hours. However, please note that the run time may vary depending on your hardware. To reduce the run time, you can try running the code with `max-epoch=200` and `stepsize=40`.

**Comment by junbum766** [comment]
thank you!
