### ISSUE TITLE
Tiny IMAGENET not present

### ISSUE THREAD

**Issue by zuliani99** [bardisafa/EOAL#4]
I found that in the argument parser there is the option of choosing the tinyimagenet dataset, however in the dataset.py there isn't any link of that.

Moreover the dictionary **__factory** do not have the tinyimagenet key:
```
__factory = {
    'cifar100': CIFAR100,
    'cifar10': CIFAR10
}
```
Maybe because the tinyimagenet is not implemented on torchvision.dataset, so how do you get and use it?

Thanks for the feedback!

**Comment by zuliani99** [comment]
Since Tiny-IMAGENET have images of size 64x64 have you used a resize to 32x32 pixels or have you changed the ResNet parameters?

**Comment by bardisafa** [comment]
Thanks for your interest in our work. Yes, we used the original 64x64 images for training on the tiny imagenet dataset.
