### ISSUE TITLE
about function  `filter_known_unknown_10percent `   

### ISSUE THREAD

**Issue by wzhuo2022** [bardisafa/EOAL#6]
Hello, when I checked your code, I noticed that when using CIFAR10, init_percent=1, but there is a function named filter_known_unknown_10percent in the code. Its function seems to be inconsistent with the name. Is it filtering out 10% or 1%? ?

**Comment by bardisafa** [comment]
Yeah you are right and the "10percent" shouldn't be a part of the function name-- probably remained from previous code versions. But the function itself is correct, and it constructs labeled and unlabeled subsets based on the given "init_percent" argument.
